In [ ]:
Dataset: Consider the following dataset of sales records:
Order ID Customer Product Category Quantity Price Total Sales
1001 Alice Laptop Electronics 2 800 1600
1002 Bob Phone Electronics 1 500 500
1003 Charlie Chair Furniture 4 100 400
1004 Alice Table Furniture 1 250 250
1005 David Laptop Electronics 1 800 800
1006 Charlie Phone Electronics 2 500 1000
1007 Bob Chair Furniture 2 100 200
1008 Alice Phone Electronics 1 500 500

In [1]:
import pandas as pd
import numpy as np

In [5]:
import pandas as pd

data = {
    "Order ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "Customer": ["Alice", "Bob", "Charlie", "Alice", "David", "Charlie", "Bob", "Alice"],
    "Product": ["Laptop", "Phone", "Chair", "Table", "Laptop", "Phone", "Chair", None],
    "Category": ["Electronics", "Electronics", "Furniture", "Furniture", "Electronics", "Electronics", "Furniture", None],
    "Quantity": [2, 1, 4, 1, 1, 2, 2, None],
    "Price": [800, 500, 100, 250, 800, 500, 100, None],
    "Total Sales": [1600, 500, 400, 250, 800, 1000, 200, None]
}

df = pd.DataFrame(data)

print(df)

   Order ID Customer Product     Category  Quantity  Price  Total Sales
0      1001    Alice  Laptop  Electronics       2.0  800.0       1600.0
1      1002      Bob   Phone  Electronics       1.0  500.0        500.0
2      1003  Charlie   Chair    Furniture       4.0  100.0        400.0
3      1004    Alice   Table    Furniture       1.0  250.0        250.0
4      1005    David  Laptop  Electronics       1.0  800.0        800.0
5      1006  Charlie   Phone  Electronics       2.0  500.0       1000.0
6      1007      Bob   Chair    Furniture       2.0  100.0        200.0
7      1008    Alice    None         None       NaN    NaN          NaN

In [6]:
df["Discount"]=df["Total Sales"] * 0.10

In [7]:
new_row={"Order ID" : 1009,
           "Customer": "Eve",
    "Product": "Tablet",
    "Category": "Electronics",
    "Quantity": 1,
    "Price": 300,
    "Total Sales": 300,
    "Discount": 30}
df = pd.concat([df,pd.DataFrame([new_row])])

In [8]:
print(df)

   Order ID Customer Product     Category  Quantity  Price  Total Sales  \
0      1001    Alice  Laptop  Electronics       2.0  800.0       1600.0
1      1002      Bob   Phone  Electronics       1.0  500.0        500.0
2      1003  Charlie   Chair    Furniture       4.0  100.0        400.0
3      1004    Alice   Table    Furniture       1.0  250.0        250.0
4      1005    David  Laptop  Electronics       1.0  800.0        800.0
5      1006  Charlie   Phone  Electronics       2.0  500.0       1000.0
6      1007      Bob   Chair    Furniture       2.0  100.0        200.0
7      1008    Alice    None         None       NaN    NaN          NaN
0      1009      Eve  Tablet  Electronics       1.0  300.0        300.0

   Discount
0     160.0
1      50.0
2      40.0
3      25.0
4      80.0
5     100.0
6      20.0
7       NaN
0      30.0

In [12]:
df[df["Category"] == "Electronics"]

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2.0,800.0,1600.0,160.0
1,1002,Bob,Phone,Electronics,1.0,500.0,500.0,50.0
4,1005,David,Laptop,Electronics,1.0,800.0,800.0,80.0
5,1006,Charlie,Phone,Electronics,2.0,500.0,1000.0,100.0
0,1009,Eve,Tablet,Electronics,1.0,300.0,300.0,30.0

In [13]:
df[["Customer","Total Sales"]]

  Customer  Total Sales
0    Alice       1600.0
1      Bob        500.0
2  Charlie        400.0
3    Alice        250.0
4    David        800.0
5  Charlie       1000.0
6      Bob        200.0
7    Alice          NaN
0      Eve        300.0

In [16]:
grouped=df.groupby('Customer')["Total Sales"].sum()
print(grouped)

Customer
Alice      1850.0
Bob         700.0
Charlie    1400.0
David       800.0
Eve         300.0
Name: Total Sales, dtype: float64

In [17]:
sorted_df = df.sort_values(by="Total Sales",ascending=False)
print(sorted_df)

   Order ID Customer Product     Category  Quantity  Price  Total Sales  \
0      1001    Alice  Laptop  Electronics       2.0  800.0       1600.0
5      1006  Charlie   Phone  Electronics       2.0  500.0       1000.0
4      1005    David  Laptop  Electronics       1.0  800.0        800.0
1      1002      Bob   Phone  Electronics       1.0  500.0        500.0
2      1003  Charlie   Chair    Furniture       4.0  100.0        400.0
0      1009      Eve  Tablet  Electronics       1.0  300.0        300.0
3      1004    Alice   Table    Furniture       1.0  250.0        250.0
6      1007      Bob   Chair    Furniture       2.0  100.0        200.0
7      1008    Alice    None         None       NaN    NaN          NaN

   Discount
0     160.0
5     100.0
4      80.0
1      50.0
2      40.0
0      30.0
3      25.0
6      20.0
7       NaN

In [18]:
df["sales Category"]=df["Total Sales"].apply(lambda x : "high" if x>1000 else "Low")

In [19]:
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount,sales Category
0,1001,Alice,Laptop,Electronics,2.0,800.0,1600.0,160.0,high
1,1002,Bob,Phone,Electronics,1.0,500.0,500.0,50.0,Low
2,1003,Charlie,Chair,Furniture,4.0,100.0,400.0,40.0,Low
3,1004,Alice,Table,Furniture,1.0,250.0,250.0,25.0,Low
4,1005,David,Laptop,Electronics,1.0,800.0,800.0,80.0,Low
5,1006,Charlie,Phone,Electronics,2.0,500.0,1000.0,100.0,Low
6,1007,Bob,Chair,Furniture,2.0,100.0,200.0,20.0,Low
7,1008,Alice,None,None,NaN,NaN,NaN,NaN,Low
0,1009,Eve,Tablet,Electronics,1.0,300.0,300.0,30.0,Low

In [20]:
df.to_csv("sales_data.csv" , index = False)