In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("cars93.csv")

In [5]:
type(data)

pandas.core.frame.DataFrame

In [6]:
data.shape

(93, 10)

In [7]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         79 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [8]:
data.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [13]:
data["AirBags"].unique()

array(['Driver only', 'Driver & Passenger', nan], dtype=object)

In [14]:
data["AirBags"].value_counts()

AirBags
Driver only           57
Driver & Passenger    22
Name: count, dtype: int64

In [8]:
res=data["AirBags"].mode()
res

0    Driver only
Name: AirBags, dtype: object

In [16]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [19]:
data["AirBags"]= data["AirBags"].fillna(res[0])

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         93 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [32]:
data.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    2
dtype: int64

In [33]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0

In [26]:
avg=data["Luggage.room"].mode()

In [27]:
data["Luggage.room"]=data["Luggage.room"].fillna(avg[0])

In [30]:
data.drop("Luggage.room", axis=1 , inplace=True )