In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [4]:
df = pd.read_csv("home_prices.csv")

In [5]:
df.describe()

       area_sqr_ft    bedrooms  price_lakhs
count   300.000000  300.000000   300.000000
mean   2371.990000    3.013333   148.050000
std     942.766953    1.446882    52.873113
min     601.000000    1.000000    15.000000
25%    1620.750000    2.000000   107.750000
50%    2342.500000    3.000000   151.000000
75%    3206.000000    4.000000   191.000000
max    3997.000000    5.000000   250.000000

In [6]:
df.head()

   area_sqr_ft  bedrooms color  price_lakhs
0         3774         2   Red          216
1         1460         3  Gray           88
2         1894         4  Gray          147
3         1730         2  Blue           84
4         1695         1  Blue           77

In [7]:
df.drop("color",axis = 1 , inplace=True)

In [8]:
df.describe()

       area_sqr_ft    bedrooms  price_lakhs
count   300.000000  300.000000   300.000000
mean   2371.990000    3.013333   148.050000
std     942.766953    1.446882    52.873113
min     601.000000    1.000000    15.000000
25%    1620.750000    2.000000   107.750000
50%    2342.500000    3.000000   151.000000
75%    3206.000000    4.000000   191.000000
max    3997.000000    5.000000   250.000000

In [9]:
x=df.drop("price_lakhs" , axis = 1)

In [10]:
from sklearn.preprocessing import StandardScaler

In [12]:
ss = StandardScaler()
x_ss = ss.fit_transform(x)

In [13]:
pd.DataFrame(x_ss).describe()

                  0             1
count  3.000000e+02  3.000000e+02
mean   2.279658e-16  7.401487e-17
std    1.001671e+00  1.001671e+00
min   -1.881641e+00 -1.393823e+00
25%   -7.981773e-01 -7.015268e-01
50%   -3.133253e-02 -9.230616e-03
75%    8.861188e-01  6.830656e-01
max    1.726540e+00  1.375362e+00