In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic_train.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df = df.drop(["PassengerId"] , axis = 1)

In [6]:
df = df.drop(["Name"] , axis = 1)

In [7]:
df = df.drop(["Ticket"] , axis = 1)

In [8]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [9]:
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [11]:
df["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [12]:
df['Deck'] = df['Cabin'].str[0]

In [15]:
df['Deck']

0      Unknown
1            C
2      Unknown
3            C
4      Unknown
        ...
886    Unknown
887          B
888    Unknown
889          C
890    Unknown
Name: Deck, Length: 891, dtype: object

In [14]:
df['Deck'] = df['Deck'].fillna('Unknown')

In [18]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked     Deck
0         0       3    male  22.0      1      0   7.2500        S  Unknown
1         1       1  female  38.0      1      0  71.2833        C        C
2         1       3  female  26.0      0      0   7.9250        S  Unknown
3         1       1  female  35.0      1      0  53.1000        S        C
4         0       3    male  35.0      0      0   8.0500        S  Unknown

In [17]:
df= df.drop(["Cabin"] , axis = 1)

In [19]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [20]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked     Deck
0         0       3    male  22.0      1      0   7.2500        S  Unknown
1         1       1  female  38.0      1      0  71.2833        C        C
2         1       3  female  26.0      0      0   7.9250        S  Unknown
3         1       1  female  35.0      1      0  53.1000        S        C
4         0       3    male  35.0      0      0   8.0500        S  Unknown

In [21]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
Deck        0
dtype: int64

In [25]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [24]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [26]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [27]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Deck        0
dtype: int64

In [28]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked     Deck
0         0       3    male  22.0      1      0   7.2500        S  Unknown
1         1       1  female  38.0      1      0  71.2833        C        C
2         1       3  female  26.0      0      0   7.9250        S  Unknown
3         1       1  female  35.0      1      0  53.1000        S        C
4         0       3    male  35.0      0      0   8.0500        S  Unknown

In [29]:
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
mean = df["Pclass"].mean()
std = df["Pclass"].std()

In [39]:
def find_outliers(df,col):
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.boxplot(df[col])
    plt.subplot(1,2,2)
    mean4=df[col].mean()
    std4=df[col].std() 
    sns.histplot(data=df , x=col , kde=True)
    plt.axvline(mean4,color="red")
    plt.axvline(mean4+3*std4 , color = "blue")
    plt.axvline(mean4-3*std4 , color="blue")

In [40]:
def show_outliers(df,col):
    q1=df[col].quantile(0.25)
    q3=df[col].quantile(0.75)
    iqr = q3-q1
    upper = q3+(1.5*iqr)
    lower=q1-(1.5*iqr)
    return df[(df[col]<lower) | (df[col]>upper)]

In [41]:
def handleOutliers(df,col):
    q1=df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr=q3-q1
    lower = q1-(1.5*iqr)
    upper = q3+(1.5*iqr)
    df.loc[df[col]>upper , col]=upper
    df.loc[df[col]<lower , col]=lower

In [45]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked     Deck
0         0       3    male  22.0      1      0   7.2500        S  Unknown
1         1       1  female  38.0      1      0  71.2833        C        C
2         1       3  female  26.0      0      0   7.9250        S  Unknown
3         1       1  female  35.0      1      0  53.1000        S        C
4         0       3    male  35.0      0      0   8.0500        S  Unknown

In [51]:
df["Sex"].unique()

array(['male', 'female'], dtype=object)

In [52]:
df["Sex"] = df["Sex"].replace({'male':0, 'female':1})

C:\Users\Admin\AppData\Local\Temp\ipykernel_9296\1695075883.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Sex"] = df["Sex"].replace({'male':0, 'female':1})

In [53]:
df["Embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [54]:
df["Embarked"] = df["Embarked"].replace({'S':0, 'C':1, 'Q':2})

C:\Users\Admin\AppData\Local\Temp\ipykernel_9296\4126414340.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Embarked"] = df["Embarked"].replace({'S':0, 'C':1, 'Q':2})

In [55]:
df["Deck"].unique()

array(['Unknown', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [56]:
df["Deck"] = df["Deck"].replace({'Unknown':0, 'C':1, 'E':2, 'G':3, 'D':4, 'A':5, 'B':6, 'F':7, 'T':8})

C:\Users\Admin\AppData\Local\Temp\ipykernel_9296\1320352122.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Deck"] = df["Deck"].replace({'Unknown':0, 'C':1, 'E':2, 'G':3, 'D':4, 'A':5, 'B':6, 'F':7, 'T':8})

In [57]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Deck
0         0       3    0  22.0      1      0   7.2500         0     0
1         1       1    1  38.0      1      0  71.2833         1     1
2         1       3    1  26.0      0      0   7.9250         0     0
3         1       1    1  35.0      1      0  53.1000         0     1
4         0       3    0  35.0      0      0   8.0500         0     0

In [58]:
df.describe()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Deck
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,0.352413,29.361582,0.523008,0.381594,32.204208,0.361392,0.811448
std,0.486592,0.836071,0.477990,13.019697,1.102743,0.806057,49.693429,0.635673,1.815143
min,0.000000,1.000000,0.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,0.000000,22.000000,0.000000,0.000000,7.910400,0.000000,0.000000
50%,0.000000,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,0.000000,0.000000
75%,1.000000,3.000000,1.000000,35.000000,1.000000,0.000000,31.000000,1.000000,0.000000
max,1.000000,3.000000,1.000000,80.000000,8.000000,6.000000,512.329200,2.000000,8.000000

In [59]:
x = df.drop(["Survived"] , axis =1 )
y= df["Survived"]

In [60]:
from sklearn.preprocessing import StandardScaler 
ss= StandardScaler()
x_ss = ss.fit_transform(x)

In [61]:
x_ss

array([[ 0.82737724, -0.73769513, -0.56573646, ..., -0.50244517,
        -0.56883712, -0.44729447],
       [-1.56610693,  1.35557354,  0.66386103, ...,  0.78684529,
         1.00518113,  0.10393564],
       [ 0.82737724,  1.35557354, -0.25833709, ..., -0.48885426,
        -0.56883712, -0.44729447],
       ...,
       [ 0.82737724,  1.35557354, -0.1046374 , ..., -0.17626324,
        -0.56883712, -0.44729447],
       [-1.56610693, -0.73769513, -0.25833709, ..., -0.04438104,
         1.00518113,  0.10393564],
       [ 0.82737724, -0.73769513,  0.20276197, ..., -0.49237783,
         2.57919938, -0.44729447]], shape=(891, 8))

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test , y_train,y_test = train_test_split(x_ss,y,test_size=0.2,random_state=37)

In [64]:
from sklearn.svm import SVC 
model = SVC()
model.fit(x_train , y_train)

SVC()

In [65]:
test_pred= model.predict(x_test)

In [66]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , test_pred)

0.8156424581005587

In [67]:
train_pred = model.predict(x_train)

In [68]:
accuracy_score(y_train , train_pred)

0.8497191011235955

In [69]:
from sklearn.model_selection import cross_validate
res= cross_validate(model , x_train ,y_train)

In [70]:
res["test_score"].mean()

np.float64(0.8132374667585935)